apiVersion: v1
kind: Service
metadata:
  name: devops-demo-api
  namespace: devops-demo
  labels:
    app: devops-demo-api
    project: devops-pipeline-demo
    environment: dev
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30080
  selector:
    app: devops-demo-api
